#!/usr/bin/env bash
#
# generate-changelog.sh — Generiert eine strukturierte CHANGELOG.md aus Git-History
# Bounty: claude-builders-bounty Issue #1 ($50)
#
# Nutzung: ./changelog.sh [optional: von-tag bis-tag]
#   Ohne Argumente: Commits seit letztem Tag → aktueller HEAD
#
set -euo pipefail

# ── Konfiguration ──────────────────────────────────────────────────────────
OUTPUT_FILE="${OUTPUT_FILE:-CHANGELOG.md}"
LAST_TAG="${1:-$(git describe --tags --abbrev=0 2>/dev/null || echo '')}"
HEAD="${2:-HEAD}"

# Kategorien und ihre Muster (zuordnung nach Commit-Message)
declare -A PATTERNS=(
  [Added]="^(feat|add|new|implement|introduce|support)"
  [Fixed]="^(fix|hotfix|bugfix|resolv|repair|patch)"
  [Changed]="^(chore|refactor|perf|improve|update|upgrade|rename|reformat|rewrite)"
  [Removed]="^(remove|delet|drop|deprecat)"
  [Docs]="^(doc|docs|document|comment|readme)"
  [Tests]="^(test|tests|spec|assert|fixture)"
  [Build]="^(build|compile|bundle|package|deps)"
  [CI]="^(ci|cd|pipeline|workflow|lint|format)"
)

# Liefert die Kategorie für eine Commit-Message
get_category() {
  local msg="$1"
  local cat="Changed"
  for pattern in "${!PATTERNS[@]}"; do
    if echo "$msg" | grep -qiE "${PATTERNS[$pattern]}"; then
      cat="$pattern"
      break
    fi
  done
  echo "$cat"
}

#主-Logik
main() {
  # Prüfe Git-Repo
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Fehler: Kein Git-Repository gefunden." >&2
    exit 1
  fi

  # Hole Commits
  if [ -z "$LAST_TAG" ]; then
    echo "ℹ️  Kein vorheriges Tag gefunden – zeige alle Commits."
    RANGE="HEAD"
  else
    RANGE="${LAST_TAG}..${HEAD}"
    echo "ℹ️  Zeige Commits von ${LAST_TAG} bis ${HEAD}"
  fi

  COMMITS=$(git log --format="%H|%s" "$RANGE" 2>/dev/null | grep -v '^$') || {
    echo "⚠️  Keine Commits gefunden." >&2
    exit 0
  }

  # strukturiere nach Kategorien
  declare -A SECTIONS
  while IFS='|' read -r hash msg; do
    [ -z "$hash" ] && continue
    cat=$(get_category "$msg")
    # Extrahiere Kurzbeschreibung ohne Typ-Präfix
    short=$(echo "$msg" | sed -E 's/^[a-z]+(\([^)]*\))?[:\s]//')
    # Kürze Hash auf 7 Zeichen
    short_hash="${hash:0:7}"
    SECTIONS["$cat"]+="- \`$short_hash\`: $short
"
  done <<< "$COMMITS"

  # Schreibe CHANGELOG.md
  VERSION="[Unreleased]"
  DATE=$(date +%Y-%m-%d)

  {
    echo "# Changelog"
    echo ""
    echo "## ${VERSION} (${DATE})"
    echo ""

    # Reihenfolge der Kategorien
    for cat in Added Fixed Changed Removed Docs Tests Build CI; do
      content="${SECTIONS[$cat]:-}"
      if [ -n "$content" ]; then
        echo "### ${cat}"
        echo ""
        echo -en "$content"
        echo ""
      fi
    done

    echo "---"
    echo ""
    echo "*Generated by [generate-changelog.sh](https://github.com/claude-builders-bounty/claude-builders-bounty)*"

  } > "$OUTPUT_FILE"

  echo "✅ CHANGELOG.md geschrieben: $OUTPUT_FILE"
  echo "   Kategorien:"
  for cat in "${!SECTIONS[@]}"; do
    count=$(grep -c "^\-" <<< "${SECTIONS[$cat]}")
    echo "   - ${cat}: ${count} Einträge"
  done
}

main "$@"
